### ISSUE TITLE
include head.html, helix-version.txt and metadata location

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-config-aggregator#9]
in order to reduce the amount of requests needed in the helix-pipeline-service, we should also include:

- `head.html`
- `helix-version.txt`

we could also consider the existence of a metadata.json as config, to avoid unnecessary 404 requests. maybe just a:

```
"metadata": {
  path: "/metadata.json"
}
```

  
@davidnuescheler WDYT?

**Comment by trieloff** [comment]
Duped by #8 and #10
